name: Build RPM Package

on:
  push:
    branches:
      - main
    paths:
      - 'rpm/**.spec'
      - '**.sh'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: centos:7 # Use CentOS 7

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install RPM build tools
        run: |
          yum install -y rpm-build rpmdevtools wget unzip
          rpmdev-setuptree

      - name: Build RPM
        run: |
          cp rpm/calculate_files.spec ~/rpmbuild/SPECS/
          cd ~/rpmbuild/SOURCES/
          wget https://github.com/shh1raii/KisterniyLabs/archive/main.zip
          cd ../../
          rpmbuild -bs --define "dist .generic" rpmbuild/SPECS/calculate_files.spec
          rpmbuild --rebuild rpmbuild/SRPMS/calculate_files-1.0-1.generic.src.rpm

      - name: Upload RPM
        uses: actions/upload-artifact@v2
        with:
          name: rpm-package
          path: |
            ~/rpmbuild/RPMS/**/*.rpm
            ~/rpmbuild/SRPMS/**/*.src.rpm
